### ISSUE TITLE
Unable to load database

### ISSUE THREAD

**Issue by Laranjeira-S** [task123/sim_db#1]
Hello, 

I am really keen to implement your toolbox within my code. 
However, unfortunately after going through the installation steps: 
1. pip install sim_db
2. sim_db list_commands
3. python -c "import sim_db"

Everything runs perfectly until here. 
Then running a simple case such as the "minimal example" I get an error in the line: 

"
import sim_db # 'sim_db/src/' have been include in the path.
# Open the database and write some initial metadata to the database.
sim_database = sim_db.SimDB()
"
The error I get is: 

"
usage: [-h] --id ID [--path_proj_root PATH_PROJ_ROOT]
: error: the following arguments are required: --id/-i
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

/Users/Simao/.pyenv/versions/anaconda3-2022.05/envs/foinicsproject/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3560: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
"

I am running the code using anaconda on a Mac using python 3.7.10.
It's quite an odd error. So completely understand if no one else has experienced it. 
Is there any suggestion you could provide to solve it? 

Thank you very much, 
Best wishes, 
Simão

**Comment by htasken** [comment]
Hey Simão,

Great to hear that you want to incorporate sim_db in your project. Let me see if I can help you do just that.

It seems like you are running `minimal_example.py` without passing it the required 'ID' number. (It needs this number to find the parameters in the database.) From the error message I can see that you are using IPython. While I don't use IPython myself, I suspect IPython turns the expected error message for omitting to pass the required `--id 'ID'` flag, into the more confusing error message you got. 

Let me first explain a tiny bit about how sim_db works and then I will walk you through how to get the minimal example to run.

sim_db works be taking a file with your parameters in a special format and stores it in a database. A python program that uses sim_db can then read these parameters from the database and use them as it want. The database can however contain a large number of these sets of parameters and program needs to know an 'ID' number to get the right set of parameters. sim_db can also run the program for you.

How to use sim_db is explained here: [https://sim-db.readthedocs.io/en/latest/use.html](url). I will however, walk you through everything I do, including all commands I run, to make minimal_example.py run in a new folder. Since I don't use IPython, I will show you the commands for doing it in  a standard terminal application and you will have to make the necessary adaption if there are any differences. 

* First I will install sim_db with: `$ pip install sim_db`. You have already done this step. 
* Then I make a new folder called 'minimal_example' with: `$ mkdir minimal_example`.
* I copy the 'params_minimal_python_example.txt' and 'minimal_example.py' files found here: [https://github.com/task123/sim_db/tree/master/examples](url) into the 'minimal_example' directory. 
* I will also change a the `run_command (string): python root/examples/minimal_example.py` line in the 'params_minimal_python_example.py' to `run_command (string): python root/minimal_example.py`. (This change is made because the minimal_example.py is located directly under the root directory of this example project, which will be the 'minimal_example/' directory, and not under a subdirectory called 'examples' as in the source code of sim_db.)

Now the groundwork is done, and I can start using sim_db.

* While I am inside the 'minimal_example/' directory, I initialise sim_db with: `$ sim_db init`, which will create a hidden database in 'minimal_example/'. 
* I will then add the parameters for the minimal example found in the 'params_minimal_python_example.txt' with the command: `$ sim_db add --filename params_minimal_python_example.txt`. It will print 'ID of last added: 1', informing you that the ID of this set of parameters is 1.
* Then I run 'minimal_example.py' directly with python as: `$ python minimal_example.py --id 1`

If 'Minimal Python example is running.' is printed, then you have successfully run the minimal example. Congratulations!

* You can also get sim_db to run 'minimal_example.py' for you as 'params_minimal_python_example.txt' have added all the necessary information in the database with: `sim_db run --id 1`. Note that sim_db don't allow you to run the same entry in the database several time, so add the '--allow_reruns' flag to allow this. The command then becomes: `$ sim_db run --id 1 --allow_reruns`. 
* You can get sim_db to add the parameters to the database and run 'minimal_example.py' in one command, eliminating the need to pass the 'ID' argument, with: `$sim_db add_and_run --filename params_minimal_python_example.txt`

In general I also recommend using the build-in help function of sim_db to discover the possible commands and flags and the correct usage. Pass the `--help` or `-h` flag to sim_db or any of its commands to print a help message such as `$ sim_db --help` or `$ sim_db run -h`.

Hope this is helpful. Let me know if you was able to make it work or if you have more questions.

Best regards,
Håkon

**Comment by Laranjeira-S** [comment]
Hello Håkon, 

Thank you very much for your prompt and detailed explanation. 
There is a mathematical model that makes use of your toolbox and it was making it impossible to use it for my research purposes. 

Thank you again, 
Best wishes, 
Simão
